# Generated by Django 3.1.5 on 2021-05-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Options',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.options'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
